import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <h1>conform-nextjs</h1>

          <h2>zod</h2>
          <ul>
            <li>
              <Link href="/zod/login">login</Link>
            </li>
            <li>
              <Link href="/zod/signup">signup</Link>
            </li>
            <li>
              <Link href="/zod/todos">todos</Link>
            </li>
          </ul>
          <hr />
        </main>
        {children}
      </body>
    </html>
  );
}
